version: "2"
services:
  php:
    container_name: php
    build: ./php
    ports:
      - "9000:9000"
    networks:
      - nginx-php
    volumes:
      - /var/www/html:/var/www/html
    environment:
      - TZ=Asia/Shanghai
    privileged: true
  nginx:
    container_name: nginx
    image: nginx:1.13
    networks:
      - nginx-php
    ports:
      - 80:80
    volumes:
      - /var/www/html:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/vhosts/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=Asia/Shanghai
    links:
      - php
    privileged: true
  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:5.6
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD: 7krYJ1bsFQ
    ports:
      - 3306:3306
    networks:
      - lnmp
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
networks:
  nginx-php: